
services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password